### ISSUE TITLE
I i make the selling amount more then one in the config it wont work. it will always only give 1 instead the amount i put in.

### ISSUE THREAD

**Issue by Allualbert** [kiranhart/Shops#1]
![image](https://user-images.githubusercontent.com/53789733/104131771-4c3ec200-5381-11eb-853a-c2f0df5f7675.png)
when i pay for this i only get one.

**Comment by kiranhart** [comment]
That's how it works. Only single items should be added. So then it works correctly according for the addition / deletion buttons

**Comment by Allualbert** [comment]
Could you add the functionality to also work with multiple items... Couse, when 64 is 10 dollars, is kinda hard to only price 1 without looking like shit.

**Comment by Allualbert** [comment]
Hay when are you done with the update? our server needs it to start testing and the release!
:)

**Comment by kiranhart** [comment]
[Shops-1.1.3-Custom.zip](https://github.com/kiranhart/Shops/files/5816345/Shops-1.1.3-Custom.zip)

I made a custom edit to the existing shops for you. It's not a public release since that's something not entirely ready for a full release. But this should work the way you want it. Any items with a stack size over 1 will sell by its total stack size and not the amount set in the GUI. But items with a stack size of 1, will go off the amount set by the user when purchasing.
